### ISSUE TITLE
[docs]: initial RELEASE / CHANGELOG document

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#10]
Hi, explorer! 🚀

We are only at the start of our adventure. Later on we are going to have more packages and multiple releases. 

Want to start the document to track these release? Just add the initial file and brief description of the document!

**Comment by Jaspreet099** [comment]
Hey, @ayoayco can you please assign this issue to me?

**Comment by ayoayco** [comment]
Thank you @Jaspreet099 for your contribution! 🚀

**Comment by ayoayco** [comment]
If you want, @Jaspreet099 - you may now create a PR to add yourself to the [list Contributors in the project README](https://github.com/ayoayco/astro-reactive-library#contributors)
