### ISSUE TITLE
feat(form): allow slotting controls into the Form component

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#106]
this will take advantage of Astro's partial hydration (for huge forms)

requires #11

```
<Form>
  <Text />
  <Checkbox />
  ...
</Form>

```

**Comment by ayoayco** [comment]
for really huge forma this will take advantage of Astro's partial hydration

**Comment by Icyscools** [comment]
After I work on #11, I noticed this is the new method to add input control types into a form.

However, I want to ask if you'll keep the current method (passing the `FormGroup` object into `Form`) or not. 
If you want to keep it, I want to ask how we should handle the case like this.
```astro
---
const form = new FormGroup([
  {
    name: "username",
    label: "Username"
  }
])

const textControl = new FormControl({
  name: "name",
  label: "Name"
});
---
<Form showValidationHints={true} formGroups={form}>
  <TextField control={textControl} />
</Form>
```
In this case, we use both methods creating a form but it got confuses. 
Should it render components from `FormGroup` or components in slot first?

**Comment by ayoayco** [comment]
Try it like this 
```
<Form showValidationHints={true} formGroups={form}>
  <TextField controlName="name" />
</Form>
```

Then in the control component, see if the `FormGroup` object of the parent is accessible and then you can just `form.get(controlName)`

**Comment by ayoayco** [comment]
Then I think we can support both, the slotted controls rendered last.

If supporting both is hard for now we prioritize slotted controls.

**Comment by ayoayco** [comment]
Hey @Icyscools if you have components for controls that take FormControl as input that's good enough for #11. :)

**Comment by Icyscools** [comment]
Great! I'll take this approach.

**Comment by ayoayco** [comment]
Closing this for now so we can focus on control components.
