### ISSUE TITLE
style(landing-page): call to action buttons

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#115]
The header section needs to be updated so that we have two "calls to action" (like in https://mui.com):
1. Get Started (primary button)
2. install text copy field

![Screen Shot 2022-10-19 at 7 15 38 AM](https://user-images.githubusercontent.com/4262489/196674842-85874093-ecbd-48df-b541-ad88b35c12b1.png)

**Comment by Lalit3716** [comment]
I can do this, can you assign this to me?

**Comment by Lalit3716** [comment]
Can you tell me exactly where you want to place these call-to-action buttons? Should I put them where I have marked?

![Screenshot 2022-10-19 172141](https://user-images.githubusercontent.com/84276404/196683317-f03ff446-b1a8-4fb2-87fc-b6009b3dd1d5.png)

**Comment by ayoayco** [comment]
Hi @Lalit3716! You can remove the Astro logo, then place the call to action buttons under the text "Build fast websites, faster."
