### ISSUE TITLE
style(landing-page): Improve responsiveness of the landing page

### ISSUE THREAD

**Issue by Lalit3716** [ayoayco/astro-reactive-library#118]
We should improve the responsiveness of the landing page right now it doesn't look good on mobile devices!

Screenshot:
![Screenshot 2022-10-20 172745](https://user-images.githubusercontent.com/84276404/196942886-5592fd3c-718b-4721-8eec-e02b4e96dac8.png)

Discussed in #112

**Comment by Preet-Sojitra** [comment]
Hey @Lalit3716 are you working on this? If not, then I want to work on this

**Comment by Lalit3716** [comment]
Sure @Preet-Sojitra, I haven't started working on this you can go ahead if @ayoayco agrees!

**Comment by ayoayco** [comment]
yes go ahead guys 👍

**Comment by Preet-Sojitra** [comment]
> yes go ahead guys 👍

Will start working on this 🚀
