### ISSUE TITLE
[feat]: create an initial project landing page

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#12]
Hey, explorer! 🚀

Let's build a fancy landing page/website for the Astro Reactive Library. Does not have to be filled with content. The only condition is that it's built with Astro, because we love Astro! :)

Astro even offers [templates](https://astro.new) and [themes](https://astro.build/themes/)!

Acceptance criteria:
1. Start an Astro project called 'landing-page'
2. Choose a fancy theme that gives you a feeling of *wonder* and *exploration* 😉

See our [contributing guide](https://github.com/ayoayco/astro-reactive-library/blob/main/CONTRIBUTING.md) on how to run our project.

Don't hesitate to ask questions if something is not clear! :)

**Comment by Preet-Sojitra** [comment]
Heyy, I want to work on this issue. 
I don't have experience of using Astro, but I want to give it try. Can you assign this to me?

**Comment by ayoayco** [comment]
Hi @Preet-Sojitra ! Awesome that you want to try Astro. I loved it the very first time I tried 😊

Let me know if I can help with anything, just ask! :)

**Comment by Preet-Sojitra** [comment]
@ayoayco Should I create the folder name "landing page" in the root of this project?

**Comment by ayoayco** [comment]
Yes, exactly. I think you can run 'npm create astro@latest landing-page' at the root

**Comment by Preet-Sojitra** [comment]
Ok will start working on this. Right now I am just creating basic landing page. Content of it can be added later

**Comment by ayoayco** [comment]
No worries! Thanks for the update! :)

**Comment by Sirsha2468** [comment]
Hi, I want to contribute for this project, can I do this?

**Comment by ayoayco** [comment]
Hi @Sirsha2468, Preet-Sojitra is already working on this. You may look for other issues or suggest another improvement for now. :)

**Comment by Preet-Sojitra** [comment]
> Hi, I want to contribute for this project, can I do this?

I am working on basic design. I will create PR soon, then you can work on the content part for the website.
