### ISSUE TITLE
bug(form): Radio groups don't work when passing more than one form group

### ISSUE THREAD

**Issue by itsagift** [ayoayco/astro-reactive-library#121]
### **Describe the bug**

- When a user passes more than one form groups to the Form component, the radio values don't show up -- instead, it simply shows the radio label with one radio button (instead of the number shown in the array).   

### **Is this a regression?**

No.

### **To Reproduce**

1. Create multiple form groups, at least one of which has an element of type "radio".
2. Add multiple values to the value property of this radio element.
3. Pass all form groups as an array to the formGroups property of form.
4.See error.

---

### **Expected behaviour**

- Expected multiple radio options/buttons to be visible.

### **Media prove**

---

WITH MULTIPLE FORM GROUPS:
<img width="169" alt="Screen Shot 2022-10-20 at 6 32 43 PM" src="https://user-images.githubusercontent.com/30632225/197071610-fc95ac4d-ccdf-4c84-b446-4c66944988e9.png">
WITH A SINGLE FORM GROUP:
<img width="125" alt="Screen Shot 2022-10-20 at 6 32 58 PM" src="https://user-images.githubusercontent.com/30632225/197071669-8a327f04-5c47-4157-bc3d-b9e23955bc75.png">

### **Your environment**

- OS: macOS Montery 12.2
- Node version: 18.0.0
- Npm version: 8.9.0
- Browser name and version: Chrome 106.0.5249.119 (Official Build) (arm64) 

---

### **Additional context**

-

**Comment by ayoayco** [comment]
thanks for reporting!

**Comment by itsagift** [comment]
I can work on this btw!

**Comment by ayoayco** [comment]
oh yeah of course! I'm thinking you can create a new `RadioGroup.astro` component to clean up `Field.astro` 

can you try this approach?

**Comment by ayoayco** [comment]
As I mentioned in #11, if @Icyscools is _cool_ with it, then the RadioGroup.astro will be taken care of there so the is issue can focus on a fix :)

**Comment by itsagift** [comment]
@ayoayco Sounds good, should probably just be handled there
