### ISSUE TITLE
feat(form): validateOnLoad prop

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#124]
Since #122 we now server-render validation errors by default. This task is for adding a prop 'validateOnLoad' for the Form component that behaves as follows:
1. if true: server-render validation errors
2. if false: do not server-render validation errors

Make the property optional, but set to true by default

**Comment by Icyscools** [comment]
I'm not quite sure about a behavior when it doesn't use server-render validation. Is it use client-side validation, or does it just render a form with no validation error messages? Can you give me more detail on this?

**Comment by ayoayco** [comment]
You will find a Validator.astro component which is reaponsible for putting on the HTML `<script>` tag containing client-side logic. That's a good place to start to understand client-side validation :)

**Comment by Icyscools** [comment]
Alright! Can I do this? I want to try. 😄

**Comment by ayoayco** [comment]
Of course!!!

**Comment by Icyscools** [comment]
@ayoayco I trying to learn our codebase a bit. 😅 If I understand correctly, each `FormControl` will do a server-render validation on the constructor, right?

**Comment by ayoayco** [comment]
Yes I think you are looking in the right place. If validateOnLoad prop is false don't proceed with the validation that happens in FormControl.

**Comment by Icyscools** [comment]
Okay! I want to ask if I can add the `validatiOnLoad` to `FormControl` and `FormGroup` in constructor parameters rather than add in Form component. I think this solution is easier for us to implement.

**Comment by ayoayco** [comment]
Hmm Maybe it will be easier for me to understand if you open a draft PR 😄
