### ISSUE TITLE
feat(landing-page): add functionality of "copy to clipboard"

### ISSUE THREAD

**Issue by Preet-Sojitra** [ayoayco/astro-reactive-library#126]
## **Feature Request**

- Currently there is `copy to clipboard` icon on the landing page. It is dummy and not functional. There is no way to copy the command pf installation. 
![image](https://user-images.githubusercontent.com/87543808/197326309-91cdff23-b269-4b4e-9c7b-0f528bfc7a06.png)

## **Describe the solution you'd like**

-  We can add functionality of copying the command to clipboard.

**Comment by CA-MKSingh** [comment]
Hey @Preet-Sojitra , I would like to work on this, can you please assign this to me?

**Comment by LeGrandMAG** [comment]
I would like to work on this feature. It would be great if  you can assign this to me.

**Comment by Preet-Sojitra** [comment]
> Hey @Preet-Sojitra , I would like to work on this, can you please assign this to me?

I don't have rights to assign the issue. @ayoayco Please assign this issue to @CA-MKSingh

**Comment by CA-MKSingh** [comment]
thanks @Preet-Sojitra and @ayoayco

**Comment by ayoayco** [comment]
Thanks @CA-MKSingh and looking forward to your PR! Just reach out if we can help :) @Preet-Sojitra and @Lalit3716 are more familiar about the landing page right now 🚀
