### ISSUE TITLE
docs: add a link to a stackblitz example

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#137]
Create a StackBlitz with example usage of our form and validator packages. 

Then update our README with a link to the StackBlitz :)

**Comment by tolkadot** [comment]
I'm going to have a go at this one.

**Comment by ayoayco** [comment]
Okay @tolkadot! 🚀 Let us know if we can help :)

**Comment by ayoayco** [comment]
Maybe codesandbox is also a good option https://twitter.com/compuives/status/1566826765699489792?s=46&t=iJO-uaIeo0jhTOpWDlvqLw

**Comment by munyanezaarmel** [comment]
@ayoayco if this issue is still going on I would like to make a PR

**Comment by tolkadot** [comment]
@ayoayco 
I've set up a code sandbox here -> https://codesandbox.io/p/github/tolkadot/astro-reactive-library/draft/sharp-lalande?file=%2Fapps%2Fdemo%2Fsrc%2Fpages%2Fpizza-delivery.astro

**Comment by ayoayco** [comment]
Yeah you're right. I will try to for it to this account then let you know

**Comment by ayoayco** [comment]
@munyanezaarmel Yes this issue is open to more than one PR. You have to create a new astro project with stackblitz or codesandbox, and use our packages. See comment above :)

**Comment by munyanezaarmel** [comment]
@ayoayco it looks like opening a whole repo in stackblitz is taking too much time  is there any how we can set like branch 
![image](https://user-images.githubusercontent.com/73389979/198383837-201b9096-21ce-4081-8c26-df8729e9ee3a.png)

**Comment by ayoayco** [comment]
@munyanezaarmel as mentioned in previous comment, you should not use this repo but instead create a new astro project of your own and install our packages from npm :)

**Comment by munyanezaarmel** [comment]
Hey @ayoayco  refer to this and tell me if am on right track https://stackblitz.com/edit/github-ze9ebb-tthuka?file=.stackblitzrc,package.json

**Comment by ayoayco** [comment]
You don't need the install script on the package.json. For stackblitz adding a dependency can be found under the Files on the side menu. See this: https://stackoverflow.com/questions/60840642/how-to-install-npm-packages-on-stackblitz

Then when you successfully add our packages as dependency, create an astro page using it. See `pages` in our `demo` app in this repo for examples :)

**Comment by munyanezaarmel** [comment]
@ayoayco by referring to this StackOverflow, not all projects have a dependency panel  if it is not there you have to modify the package.json manually

**Comment by ayoayco** [comment]
Ah hmm then I guess try to add our packages in the dependencies manually. Wait let me check your package.json :)

**Comment by munyanezaarmel** [comment]
here https://stackblitz.com/edit/github-ze9ebb-tthuka?file=package.json%3AL2,src%2Fpages%2Fpizza-delivery.astro

**Comment by ayoayco** [comment]
That looks right! Does it build?

**Comment by munyanezaarmel** [comment]
Do you mean I have to add a build script check this how I added pizza page  https://stackblitz.com/edit/github-ze9ebb-tthuka?file=package.json%3AL2,src%2Fpages%2Fpizza-delivery.astro

**Comment by ayoayco** [comment]
It looks good, I think you just have to remove the `npm install` script at the "start" script:
```
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview"
  },
```

**Comment by ayoayco** [comment]
You may also need to update the astro version, I noticed you have an older version... your package.json should look something like this:

```
{
  "name": "@example/minimal",
  "type": "module",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "astro": "^1.6.0",
    "@astro-reactive/form": "^0.5.1",
    "@astro-reactive/validator": "^0.1.0"
  }
}

```

**Comment by munyanezaarmel** [comment]
@ayoayco  i think stackblitz  needs to install packages every time page reloads by removing the npm install am getting error 
![image](https://user-images.githubusercontent.com/73389979/198566567-9b7357c7-75d4-4bc0-8a29-dfd3b356867a.png)

**Comment by ayoayco** [comment]
Reopened for a codesandbox example :)

**Comment by munyanezaarmel** [comment]
@ayoayco check this https://codesandbox.io/s/astro-reactive-library-u72dgj?file=/package.json
