### ISSUE TITLE
feat(landing-page): Add Main Section

### ISSUE THREAD

**Issue by Preet-Sojitra** [ayoayco/astro-reactive-library#138]
Currently we have discussion #112  regarding landing page. There @ayoayco has post the regarding the content of landing-page and design which looks like this 👇 .

![image](https://user-images.githubusercontent.com/87543808/197457703-6b0bf582-e4c0-4f1b-8747-dc8406f384fb.png)

Regarding Main section first of all we have to thought of some good color palette, so that we can move forward.

**Comment by ayoayco** [comment]
I think you can experiment with the color palette, as long as it plays well with the color of our logo. :)

**Comment by Preet-Sojitra** [comment]
@ayoayco You have desgined the logo of astro-reactive-library? I want the logo th

**Comment by ayoayco** [comment]
The logo is in .svg format, and can be found in `.gihub/assets`

I did not design it though, was contributed by a contributor :)

**Comment by Preet-Sojitra** [comment]
Update: I am busy in my studies so I won't be able to complete this task quickly. I have completed more than 60% of the work. So if anybody want to work on this issue can take this issue, else I will work on it once my exams gets over. So @ayoayco for now you can unassigned me from this issue.

**Comment by ayoayco** [comment]
Hey @Preet-Sojitra thanks for letting us know. No worries we all take tasks in this project in our own pace. Just pop in and out of discussions when you can. Hope you have great exam results! 🤗

**Comment by ayoayco** [comment]
Since we are holding back on adding solid as dependency, the remaining things to do in this task are
- Display project logo
- main section with light bg
- show astro section (currently commented out)

No need to show astro and solid logos, and we can keep the simple text that we currently have "Astro. Reactive"

**Comment by Preet-Sojitra** [comment]
@ayoayco My exams are over. So am now back on this issue. 

So what are the changes to make? I think we are not adding those Astro and Solid js logo

> Currently we have discussion #112 regarding landing page. There @ayoayco has post the regarding the content of landing-page and design which looks like this 👇 .
> 
> ![image](https://user-images.githubusercontent.com/87543808/197457703-6b0bf582-e4c0-4f1b-8747-dc8406f384fb.png)
> 
> Regarding Main section first of all we have to thought of some good color palette, so that we can move forward.

@ayoayco  My exams are over , so I am back on this issue. So what are the changes in the design?  I think we are not adding those rotating logos which are shown on the right in the design? All others things are same?
