### ISSUE TITLE
refactor(form): deprecate `labelPosition` prop

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#139]
Remove the `labelPosition` prop, and implement the following:
1. By default labels are on the left
2. For checkboxes, labels are on the right

This is in preparation for implementing an RTL flag later for localization.

**Comment by Icyscools** [comment]
If this issue still opening, you can assign this to me. 😄

**Comment by ayoayco** [comment]
Alright! :)
