### ISSUE TITLE
feat(form): implement unique IDs

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#140]
Right now we use the 'name' value for FormGroup and FormControl to add IDs. We will have problems if users don't give unique names in their configuration, which is likely to happen. For this reason, internal IDs should not depend on the configuration.

The name should stay the same, where we use what is provided by the configuration. However, for IDs, we need to make sure they are unique because we use them as selectors.

Implement the following so that the IDs are unique:
1. internal IDs should not depend on the `name` prop
2. create a function that generates a short unique ID
3. prefix with `arl` (e.g., `arl-fjkdlsafj`)
4. make sure labels use this for the `for` attribute has the same value as the input's `id` (i.e., the generated ID)

From [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label):
> To associate the `<label>` with an `<input>` element, you need to give the `<input>` an id attribute. The `<label>` then needs a for attribute whose value is the same as the input's id.

**Comment by alexsam29** [comment]
HI, I've been looking through the code and I think I understand how this works. I could give it a try.  

I found a NPM library that can generate short unique IDs (https://github.com/simplyhexagonal/short-unique-id). Would I be able to use that for IDs or do you want a custom function made?

**Comment by ayoayco** [comment]
Hi @alexsam29 I think that should be okay! Let me know how it goes :)
