### ISSUE TITLE
feat(form): Dropdown control

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#143]
We don't have support now for a dropdown 😅

- Implement a new `dropdown` control type with configuration properties similar to the discussed configuration of radio in #142 
- Create a new `Dropdown.astro` control component that will be rendered when `control.type` is dropdown (see implementation for `RadioGroup.astro`
- `Dropdown.astro` will render `<select>` and several `<option>` tags depending on the control  configuration

**Comment by Icyscools** [comment]
Can I work on this?

**Comment by ayoayco** [comment]
Yes of course @Icyscools :)
