### ISSUE TITLE
feat(form): readOnly flag

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#144]
Implement a new `readOnly` boolean prop for the `Form.astro` component. When true, all fields are then rendered as uneditable. 

✨ Take note : not disabled, but readonly.

**Comment by AllanSiqueira** [comment]
Can I work on this? :)

**Comment by ayoayco** [comment]
Hi @AllanSiqueira! Sure, let us know if something is not clear :)
