### ISSUE TITLE
chore: create script for updating RELEASE.md before PR

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#148]
✨ Desired outcome: easily update correct RELEASE.md file for a change that a PR will bring

Running the script should be able to
1. ask for scope and type of change the PR will bring in
2. correctly identify the appropriate RELEASE.md file
3. ask for message
4. write message to appropriate section of the file (fix or feat)

The script could later be used for automating update of change logs depending on PR title :)

**Comment by NeilAn99** [comment]
Hey, I would be interested in this, but I have a couple questions. 
1. Should the script be run by the user before they create a PR? Something like `npm run release` and then they enter in the details?
2. Where should the RELEASE.md file and the script file be located?

**Comment by ayoayco** [comment]
> 1. Should the script be run by the user before they create a PR? Something like `npm run release` and then they enter in the details?
Yes, the contributor will run it before a PR. One of the questions will be which package was affected: form / validator.

> 2. Where should the RELEASE.md file and the script file be located?
Depending on the package selected, you will find a RELEASE.md file (eg, packages/form/RELEASE.md for the form package)

Also think of the scenario where PRs affect multiple packages. Should the contributor re-run the script or can you have a prompt like `how many packages are affected?` or `do you want to update another package release?`

@NeilAn99
