### ISSUE TITLE
test(validator): add tests for all validator functions

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#149]
✨ Desired outcome: 100% test coverage for the validator functions ;) see the file in `packages/validator/core/validator-functions.ts`

**Comment by vancassa** [comment]
Hi, may I work on this?

**Comment by ayoayco** [comment]
Sure @vancassa! Looking forward to a PR :)

**Comment by vancassa** [comment]
I'm sorry, I've looked at the repo and tried some stuff but it seems to be beyond me. I'll unassign myself so others can take on this issue instead.

**Comment by Lalit3716** [comment]
Hi, I would like to take this one @ayoayco?

**Comment by Lalit3716** [comment]
Hey @ayoayco, wanted to know if I am allowed to add some libraries for this task like ts-node/ts-mocha because I can't import validator functions in test files before transpilling Typescript. Or if you have some better suggestions do let me know!

**Comment by ayoayco** [comment]
Oh I didn't know that. Yes pls add what you need as a dev dependency :)

**Comment by Lalit3716** [comment]
Hi @ayoayco, I tried everything (ts-mocha, changing compiler options in tsconfig, etc...) but nothing is working out for me. I just can't import external typescript files inside test files 😭. Should I open a draft-pr with my latest changes so that you can have a look at what I have tried so far ?

**Comment by ayoayco** [comment]
Oh yeah maybe I can help if you open a draft PR :)

**Comment by ayoayco** [comment]
Thank you @Lalit3716 -- we now know that this issue is not ready. I need to reassess our test tooling. Thanks a ton!!
