### ISSUE TITLE
[chore]: Add contributor pictures to the project README

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#16]
Hi, explorer! 🚀

The [list of contributors in our project README](https://github.com/ayoayco/astro-reactive-library#contributors) needs to be in sync. For this, we can use: [https://contrib.rocks](https://contrib.rocks)

Update our readme to embed the image generated by [https://contrib.rocks](https://contrib.rocks) for the project repository to fix this issue :)

**Comment by ManasviGoyal** [comment]
Hi. I would like to work on this

**Comment by snehafarkya** [comment]
Hey! Can I work on this?

**Comment by Udeozor** [comment]
Hi, I would like to take up this issue.

**Comment by ayoayco** [comment]
Hi @ManasviGoyal @snehafarkya @Udeozor ! Thank you for your interest to contribute! 🚀

We now have an open PR #17 for this, which just needs one minor adjustment... I am just waiting for the update and it will be merged.

You may look into other open issues for anything you are interested to do 🤗 or you can always open a new issue if you find something to improve.

**Comment by adetoye-dev** [comment]
> Hi @ManasviGoyal @snehafarkya @Udeozor ! Thank you for your interest to contribute! 🚀
> 
> We now have an open PR #17 for this, which just needs one minor adjustment... I am just waiting for the update and it will be merged.
> 
> You may look into other open issues for anything you are interested to do 🤗 or you can always open a new issue if you find something to improve.

Hi, thanks for checking out my PR, what adjustments do I need to make so I can go fix it ASAP?

**Comment by ayoayco** [comment]
Thanks @adetoye-dev , I just put a comment to your PR! :)
