### ISSUE TITLE
feat(form): add a TextArea control

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#161]
✨ Desired outcome: a new `TextArea.astro` component that will be rendered when the `Control.type` is 'textarea'

You will also need to implement an interface in control.types.ts which should define the control props that a TextArea could take. It extends the ControlBase and also adds some new props: `rows` and `cols`

The `TextArea.astro` should render a textarea HTML element

See pattern of changes in discussions for Dropdown and Radio:
- #143 
- #142

**Comment by Icyscools** [comment]
Hi @ayoayco, Can I work on this?

**Comment by ayoayco** [comment]
Hi @Icyscools of course!

**Comment by Icyscools** [comment]
What should the default values for `rows` and `cols` be?

**Comment by ayoayco** [comment]
Good question. 3 rows is good then you can play around the cols so it is close to default with of a text input :)
