### ISSUE TITLE
feat: add a new demo page!

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#162]
Hi, explorer! 🚀

We have a demo app to play around with the packages.

Why not add some new real-life example? Create a new .astro page in the pages folder of the demo app (found in `apps/demo`). This new page will then be accessible on the browser. :)

For example, if you create a `retreat-survey.astro` file in the pages directory, just open the address in the browser: http://localhost:3000/retreat-survey

See our contributing guide for instructions to run the development server.

That's it! :)

Acceptance criteria:
- a new .astro page in the demo app with as many different form control types as you can
- add the link to your new page into the index.astro page

**Comment by NeilAn99** [comment]
Hi, can I work on this?

**Comment by NeilAn99** [comment]
Created a pull request, let me know if I need to change anything! #164
