### ISSUE TITLE
feat(validator): validation categories: error, warning, info

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#168]
Not all validation result should be an error. Think of weak passwords. Or some warning that the value is near a threshold. 

Implement a `category` prop to setting up validators that, when invalid is triggered, will set the correct attribute. 

Right now we set `data-validation-haserror`. The goal is to have other two
- `data-validation-warning`
- `data-validation-info`

`showValidationHints` will now render orange for warning and green for info

Like traffic lights. 😁

🔴🟠🟢

**Comment by Lalit3716** [comment]
Hi @ayoayco, I want to try this can I proceed?

**Comment by ayoayco** [comment]
Alright! 💪

**Comment by Lalit3716** [comment]
Hi @ayoayco, I wanted to confirm that do you want this category prop on the `Form` component right?
Or maybe you want it on validation level?
For e.g
<br>
![Screenshot 2022-11-15 001139](https://user-images.githubusercontent.com/84276404/202201892-52b84050-86b2-4524-bcfc-0d69e7d95032.png)

**Comment by ayoayco** [comment]
Good question! I totally should have clarified more. This is what I'm thinking, but you can of course explore if it is possible: We support what we currently have now (so that the current API should not break) and also something support this

```typescript
const form = new FormGroup([
{
  name: 'username',
  label: 'Username',
  validators: [{
    validator: Validators.required
    category: 'warning'
  }]
}
])
```

So it would be similar to how we implement the 'options' property for a dropdown, we support both a single string or an object with a `value` and `name ` property.

Let me know how it goes!

**Comment by Lalit3716** [comment]
Alright I will try to implement it that way, thanks for clarifying!
