### ISSUE TITLE
feat(common): types and autocompletion

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#188]
We want to do some exploratory investigation to see how we can improve developer experience with regards to using our packages in terms of the types we provide and autocompletion on VS Code

**Comment by fazzaamiarso** [comment]
@ayoayco I will look into this.

**Comment by ayoayco** [comment]
Thanks @fazzaamiarso!

**Comment by ayoayco** [comment]
For this one it would be good to imagine you are our user... so maybe create a new app from scratch so you will see the experience from installation. :)

**Comment by fazzaamiarso** [comment]
@ayoayco this issue will take a bit more time then I intended to. I'm currently experimenting with compiling typescript files and breaking up the configs to packages like this [https://turbo.build/repo/docs/handbook/linting/eslint](https://turbo.build/repo/docs/handbook/linting/eslint)

**Comment by ayoayco** [comment]
Oh no worries, no need to hurry on this if needed for quality :) let us know if you need help or some input!

**Comment by ayoayco** [comment]
One idea for this is to ads TSDoc on all our exports. It will show up on VS Code when users hover on our types, for example.

**Comment by fazzaamiarso** [comment]
> One idea for this is to add TSDoc on all our exports. It will show up on VS Code when users hover on our types, for example.

Great Idea! I will implement it. Just correct me if some descriptions aren't right.
