### ISSUE TITLE
chore(docs): change a site option in docs config

### ISSUE THREAD

**Issue by Icyscools** [ayoayco/astro-reactive-library#190]
Hi, I have noticed a recent PR (#189) doesn't pass **Mixed content - astro-reactive-docs**. 

I have looked in a [Netlify log](https://app.netlify.com/sites/astro-reactive-docs/deploys/636e87e278ce1e0008faa558) and tried to build the docs in a current main branch. 
As a result, I found out the build files have `http://astro.build` in the header as a canonical link within our docs site.

This is because Astro uses the domain in site option to generate a sitemap and canonical URLs which well document in [here](https://docs.astro.build/en/reference/configuration-reference/#site), so we have to change the site option in docs config (`astro.config.mjs`) to our domain name.

**Comment by ayoayco** [comment]
Great observation @Icyscools! Thanks for looking into this and reporting!

**Comment by Icyscools** [comment]
I can do it. 😄
