### ISSUE TITLE
docs: create initial documentation of Validators

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#195]
Who wants to try writing some docs? I will help in completion so don't worry about it being incomplete at first. :)

In this issue, add a new `validators.md` file in the API docs with the title `Validators`

In this new doc, add a section for each of the functions in the Validators class found in `/packages/validator/core/validator-names.ts`

Bonus points if you write a good description of the functions! 

Run: `npm run docs` to start the dev server for our docs site. 🚀

**Comment by Lalit3716** [comment]
I will write some initial docs for validators 📃
