### ISSUE TITLE
feat(landing-page): show toast message feedback for copy button 

### ISSUE THREAD

**Issue by Lalit3716** [ayoayco/astro-reactive-library#197]
## **Feature Request**
Add a toast that says 'Copied' when the user clicks on the copy button.

## **Is your feature request related to a problem? Please describe.**
Currently, when a user clicks on copy button on the landing page, there is no visual indication that the text has been copied which can be confusing for the users.

## **Describe the solution you'd like**
I'd like to have a toast that says copied when a user clicks on the copy button and then automatically disappears after a couple of seconds(2sec).

**Comment by ayoayco** [comment]
Thanks for creating the issue @Lalit3716!

Do you think it's possible to have a fun animation when the buttons is clicked? Like sparkles? ✨ 🤪

**Comment by Lalit3716** [comment]
Yeah probably but it maybe be hard to it without any third party animation lib 😅
