### ISSUE TITLE
[chore]: Set up the project monorepo

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#2]
Hey, explorer! 🚀

Currently, the project is made up of [NPM workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces), which are node projects that share a singular root package.

This issue is for setting up the project monorepo. Check the [CONTRIBUTING document](https://github.com/ayoayco/astro-reactive-library/blob/main/CONTRIBUTING.md) for how to contribute.

Acceptance criteria:
1. Recommend a monorepo library (e.g., Nx or Turborepo), indicating some rough pros and cons
2. Set up the agreed monorepo

That's it :) Another issue is for updating the docs to reflect the changes from this issue 👉 #3

**Comment by danicunhac** [comment]
1. https://github.com/lerna/lerna
### Pros
- It's highly maintained and stable
- It's recommended for big and long term projects
- Uses npm and TypeScript
- Has good tools and docs for developing

### Cons
- Not fully TypeScript setup
- Setup can be more difficult than Yarn Workspaces
- Less popular than Yarn Workspaces

**Comment by ayoayco** [comment]
Thank you for the detailed comment about Lerna, @danicunhac! 🚀

I am admittedly not very familiar with monorepos so this is one thing the project needs help for. I want to wait for more inputs regarding this just to have a bit more confidence in our decision. :)

**Comment by fazzaamiarso** [comment]
Hey @ayoayco, How about TurboRepo? It seems fast and reliable. Astro's repo also migrated to turborepo.

 Although it's ridiculous as I'm not familiar with Monorepo, I would like to help with this issue and learn as I go.

**Comment by ayoayco** [comment]
> Hey @ayoayco, How about TurboRepo? It seems fast and reliable. Astro's repo also migrated to turborepo.

Heard good things about turborepo as well. If Astro uses it i think it's a good idea to follow since we have tests for Astro components in our pipeline.

>  Although it's ridiculous as I'm not familiar with Monorepo, I would like to help with this issue and learn as I go.  

Yeah I don't really expect you to know everything before taking this on :) but can you also document instructions on how to use the tooling so it is easy for future maintainers to pick up?

**Comment by fazzaamiarso** [comment]
> but can you also document instructions on how to use the tooling so it is easy for future maintainers to pick up?

Sure thing! Should I document it in a new markdown file or in contributing.md?

**Comment by ayoayco** [comment]
Let's have it in a new file, going to be for maintainers rather than contributors later. :)

Don't hesitate to put here some ideas/questions. This task might need some iterating to get full implementation, but it will be a significant improvement in our project! 🚀

**Comment by fazzaamiarso** [comment]
@ayoayco I've made a minimal working setup PR. I think we should bundle `packages` so they can be optimized (e.g. minified). We can use [tsup](https://tsup.egoist.dev/#what-can-it-bundle) as bundler.

and I'm also thinking to setup versioning per this guide [https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing](https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing).

What do you think?

**Comment by ayoayco** [comment]
Thank you! I checked the PR and have some questions. I think we should also have an experiment branch for this first. So we can all have a test with the new set up first before we merge to master. I will set this branch up.

**Comment by ayoayco** [comment]
Let's use the branch `feat-turborepo-dev` 🚀 You can change your PR to target this branch instead of `main`

**Comment by fazzaamiarso** [comment]
@ayoayco can I try something? could you publish an experimental version with turborepo by using `npm publish --tag experimental` in turborepo branch so we can test it out? for reference [https://formidable.com/blog/2020/publish-npm-packages/](https://formidable.com/blog/2020/publish-npm-packages/)

I will make the PR with bumped up version of the packages.

**Comment by ayoayco** [comment]
Yup! Anything you think we need just point the PR to the branch `feat-turborepo-dev`

**Comment by ayoayco** [comment]
Then let me know what I can do on my end :)

**Comment by ayoayco** [comment]
Ah got it. Thanks for clarifying that one, now I know what to look out for. ;)

**Comment by ayoayco** [comment]
Published experimental versions of our packages (common, form, validator) @fazzaamiarso

**Comment by ayoayco** [comment]
I think everything works!
