### ISSUE TITLE
feat(form): implement FormControl and ControlConfig prop `triggerValidationOn`

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#201]
`triggerValidationOn` prop will determine when the event for validation on the client will fire.

Right now we only attach an event listener for `onBlur`.

**Comment by alexsam29** [comment]
Hi, I may want to work on this, but I'll need some further explanation if possible. I get it, but at the same time I'm slightly confused.

**Comment by ayoayco** [comment]
In the `Validator.astro` component, found in `packaged/validator`, you will find a `<script>` where the event listener for the browser is initialized.

Right now the event listener is only attached for `onBlur`

This issue is to enable other events like type onKeyPress

You may need to create a type, like:

```
export const type ValidationHooks = 'onBlur' | 'onKeyPress'; // add more
```

**Comment by alexsam29** [comment]
hmmm...Okay I get that part. What I'm most confused about is the prop `triggerValidationOn` that you mentioned.  So you'd want a new boolean variable in `form-control.ts` that will determine if validation occurs?

**Comment by ayoayco** [comment]
Ah no, it's not boolean. It should take a value of type `ValidationHooks` (ie, 'onBlur', 'onKeyPress', etc)  

Maybe the property name is not very good? :)

**Comment by fazzaamiarso** [comment]
Basically, we want to enable more listeners to trigger the validation. The listeners will be typed in `ValidationHooks` and users can use choose which listeners they want to use by passing `triggerValidationOn`.

Do I understand it correctly @ayoayco?

**Comment by ayoayco** [comment]
Yes exactly @fazzaamiarso
