### ISSUE TITLE
[bug]: class FormGroup get method not defined in the demo app 

### ISSUE THREAD

**Issue by amit-ksh** [ayoayco/astro-reactive-library#21]
![astro-reactive-lib](https://user-images.githubusercontent.com/91947037/193487048-b7cc4feb-bce4-4442-99a2-0abb62078a57.png)

**Comment by ayoayco** [comment]
Hi @amit-ksh thank you for reporting. I think I found the issue.

**Comment by ayoayco** [comment]
Please update your main branch and check again :)

`git pull origin master`

**Comment by ayoayco** [comment]
I see that the demo app is not using the local version of packages. I am fixing this.

**Comment by ayoayco** [comment]
Hi, @amit-ksh can you try pulling the latest main branch and doing a clean install?

```
git pull origin main
```

```
npm ci
```

**Comment by amit-ksh** [comment]
Now it working

**Comment by ayoayco** [comment]
Thank you so much for reporting! 🚀
