### ISSUE TITLE
generate a favicon.ico for our apps

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#216]
Right now we are still using Astro framework's logo as icon (favicon.ico) for our apps. Shame. 😅

Please upload a version of our logo (found in .github/assets/logo) and update the icons for our apps (found in apps/)

**Comment by NeilAn99** [comment]
Hey, I can work on this.

**Comment by ayoayco** [comment]
Thanks @NeilAn99 let us know how it goes!

**Comment by Preet-Sojitra** [comment]
> Hey, I can work on this.

Hey, you can also join our discord server to geek out with us. Here's the link: https://discord.gg/KmhXR7mXWb
If you face any difficulty you can ask here or on discord server.

**Comment by NeilAn99** [comment]
Hey, I have updated the icons. Here is what it looks like in Chrome:
![image](https://user-images.githubusercontent.com/54966170/204962022-e4221e85-b957-487a-adf0-08026a91d209.png)
and in Firefox:
![image](https://user-images.githubusercontent.com/54966170/204962249-e98bbfa4-da1a-4c24-abbe-0b0317ac0e58.png)
Let me know if it looks good to you or if you want any changes.
