### ISSUE TITLE
[chore]: Set up the github Pull Request template

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#22]
We want all Pull requests to be of quality. Let's have a basic template for all pull requests.

**Comment by chinmayayy** [comment]
Hi @ayoayco , I could contribute to this under Hacktoberfest 2022, thanks!

**Comment by ayoayco** [comment]
Hi @chinmayayy thank you for your interest to contribute to the project!

However I am already working in this issue. There are still other open issues you can check for something you want to do.

Or if you want to suggest any improvement you can create an issue for yourself too! 🚀

What do you enjoy doing? :)

**Comment by chinmayayy** [comment]
Sure! thanks
