### ISSUE TITLE
docs(validator): Validator.min and .max examples

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#229]
https://docs.astro-reactive.dev/en/api/validator/validators/#validatorsmin

☝️ the example code for `Validators.min` and `Validators.max` are better with `type: number`

```ts
const form = new FormGroup([
  {
    name: "price",
    label: "Price",
    type: "number",
    validators: [Validators.min(8)],
  },
]);

```

**Comment by Preet-Sojitra** [comment]
Ok so we just have to add `type: "number"` ? 
I can work on this
