### ISSUE TITLE
form action for submit

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#236]
Add an action prop to the form component to handle submit

**Comment by Icyscools** [comment]
How should a form action attach to  the `Submit` or `Form` component? And, what attribute name should it be? (perhaps onSubmit?) 🤔

**Comment by ayoayco** [comment]
I think we should stick to the standard of putting action in a form, so an "action" property in the Form component makes sense, then it can be overridden by a form-action property of the submit button

for reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-action

**Comment by Icyscools** [comment]
Ok, I get it! I'll work on this.

However, I think it should have a property that lets developers create their listeners to listen to the form event, etc. on click, on reset, or on submit (which is in this case). It should make our library more flexible.

**Comment by Icyscools** [comment]
Also, I just notice that we should have a `method` property for sending form data to an action URL by selecting HTTP request methods. 😄
