### ISSUE TITLE
[chore]: implement initial recommended community standards

### ISSUE THREAD

**Issue by orama254** [ayoayco/astro-reactive-library#26]
Hello @ayoayco 

I was going though this project and noticed that there are some missing items based on the [Github Community Standards recommendations](https://github.com/ayoayco/astro-reactive-library/community) that would make the project contributor friendly, e.g. a code of conduct, a license, an issue template and a pull request template.

I've seen you are working on the pull request template on issue #22. Let me know if you want help with the other items on the list.

**Comment by ayoayco** [comment]
That's really great observation, @orama254! I became aware of this too very recently.

Yes, having the initial code of conduct will help a lot. Looking forward to a PR! 🚀
