### ISSUE TITLE
[style]: implement dark and light mode for the Form component

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#28]
Hi, explorer! 🚀

This one is fun! Right now, the Form component is unstyled, and we need some CSS maneuvers to implement the very first themes: light and dark mode.

Find the file `Form.astro` inside the package `astro-reactive-form` and you will see some instructions.

✨ HINT: Use the built-in CSS property: `color-scheme`
https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

Acceptance criteria
1. `<form>` is able to switch between light and dark mode given the appropriate class attribute value
2. The tests are passing (see CONTRIBUTING.md)

**Comment by AshuwinB** [comment]
Hey ayoayco! will u assign me this issue

**Comment by ayoayco** [comment]
Hi @AshuwinB glad to have you here! 🚀

You are welcome to submit a PR for this one :)

**Comment by ayoayco** [comment]
Sure thing, @KIET7UKE 🚀 Let me know if I can help :)

**Comment by KIET7UKE** [comment]
So, Can I make PR on this?

**Comment by ayoayco** [comment]
Yes you can submit a PR for this @KIET7UKE

**Comment by KIET7UKE** [comment]
Hey, @ayoayco I have made a PR on this issue. Kindly verify 
https://github.com/ayoayco/astro-reactive-library/pull/46

**Comment by ayoayco** [comment]
✨ HINT: Use the built-in CSS property: `color-scheme`
https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
