### ISSUE TITLE
[feat] implement FormControl states

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#4]
Implement the following form control states:
- `isPristine` - boolean that is true until the control is touched, set to false when touched for the first time
- `isValid` - boolean, true until set to false by a validator (validators are implemented in another issue)

**Comment by Johnoris** [comment]
I would to work on this, please assign it to me

**Comment by ayoayco** [comment]
Sure @Johnoris give it a shot! 🚀

We don't have validators yet so you can leave it as true for now.

**Comment by Johnoris** [comment]
I am getting errors and I am not familiar with this .astro I just saw the code base .Please reassign to someone else

**Comment by ayoayco** [comment]
If you want to try more maybe you just need to update and do a clean install

git pull origin main

npm ci

**Comment by fazzaamiarso** [comment]
Hi, @ayoayco can I help with this issue?

**Comment by ayoayco** [comment]
hi @fazzaamiarso, great to have you here! 🚀

Yes this is still open. Looking forward to a PR! :)

**Comment by fazzaamiarso** [comment]
@ayoayco I got it working , but I have to use dataset on the input field for non-primitive attributes (e.g. `data-is-pristine`, `data-is-valid`).  Also, we can't touch the server side JS (script in fence) after load and we must use client-side JS to make changes to `isPristine`.

Another issue is that the form control instances that is created in server-side must be passed through `define:vars` that stringify the controls and strip off the methods from them in client. We also need to re-instantiate the `FormControls`.

What do you think?

**Comment by ayoayco** [comment]
I think it makes sense to have client-side JS for this.

The plan I have in mind is to support these kinds of features on the client side for now then we improve later providing a flag to do things server-side. Astro has capabilities for this but we can think of SSR later.

Thanks for putting great thought into this. Excited to see your PR :)

**Comment by fazzaamiarso** [comment]
@ayoayco what are your thoughts about this?  it's still messy but it have all the functionality.

[https://github.com/fazzaamiarso/astro-reactive-library/commit/ae67a532e517bebbd3b5e3d4eaf63f2fd61b7cec](https://github.com/fazzaamiarso/astro-reactive-library/commit/ae67a532e517bebbd3b5e3d4eaf63f2fd61b7cec)
