### ISSUE TITLE
[test]: add some tests for Field and FieldSet

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#41]
Hi, explorers! 🚀

Are you up for some testing challenge? Right now we only have a set of tests for Form.astro component.

We want to add the first tests for Field.astro and FieldSet.astro 🎉

You may see the file inside `packages/astro-reactive-form/tests` for an example to follow. 

Acceptance criteria:
- have tests for Field and FieldSet components when you run `npm test`

**Comment by aswinikalyan30** [comment]
Hey, would like to work on this!

**Comment by ayoayco** [comment]
Awesome, @aswinikalyan30 ! Let me know if I can help :)

**Comment by ayoayco** [comment]
Hi @aswinikalyan30 how are we doing with this one? :)

**Comment by Lalit3716** [comment]
Is it in progress if it is not then maybe I could write some tests?

**Comment by ayoayco** [comment]
This issue has been stale for a while. I think it's safe to say you can work on this @Lalit3716 -- assigning to you
