### ISSUE TITLE
[feat]: implement placeholder prop for FormControl

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#43]
Hi, explorer! 🚀

In this issue, we add a `placeholder` property for FormControl. 

Acceptance criteria 
- FormControlBase new optional prop `placeholder`
- FormControl handling for the new prop (see examples in form-control.ts)
- Field.astro component renders the input placeholder

**Comment by fazzaamiarso** [comment]
I will work on this
