### ISSUE TITLE
Want to help you by adding CheatSheet in Your Repository.

### ISSUE THREAD

**Issue by nihal-soni** [ayoayco/astro-reactive-library#44]

**Comment by ayoayco** [comment]
Hi @nihal-soni thank you for the interest to contribute! 🚀

What cheatsheet do you have in mind exactly?

**Comment by nihal-soni** [comment]
Like Html, CSS, JAVA FUNDAMENTALS , XML
This will be very helpful for beginner.

**Comment by ayoayco** [comment]
Ah these materials are not directly related to the project, and could be found in other places.

Maybe update the contributing document to add some links?
