### ISSUE TITLE
[docs]: add links to docs

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#49]
Update the CONTRIBUTING doc to add links:

1. Link to Discussion tab

```
💬 Check our Discussion board for announcements or post messages yourself.
```

2. Link to Code of Conduct

```
🏘️ See our community's Code of Conduct
```

**Comment by con-mark** [comment]
I can take this

**Comment by yash-sharma13** [comment]
please assign it to me

**Comment by ayoayco** [comment]
Hi @yash-sharma13 glad you want to contribute!

There's already an open PR for this, I am just waiting for small changes and it will be merged. 

Can you check other issues for something you want to do? Or you can report a new issue if you have an idea.
