### ISSUE TITLE
[feat]: radio set FormControl

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#5]
radio buttons are form controls that are grouped together, and allow only one to be selected. 

Implement the property that indicates the group too which a radio button belongs with, and allow only one button to be selected in this group

**Comment by Icyscools** [comment]
Hi @ayoayco, Can I work on this issue?

My first idea is to make the radio buttons can be accepted and rendered the value like this

```js
{
    name: "agreement",
    label: "Agreement",
    type: "radio",
    value: ["yes", "no"] // string[]
}
```
and you can custom the label next to the radio like this
```js
{
    name: "agreement",
    label: "Agreement",
    type: "radio",
    value: [
      { label: "Agree", value: "yes" },
      { label: "Disagree", value: "no" }
    ]
}
```

What do you think?

**Comment by ayoayco** [comment]
Hi @Icyscools it looks good! Let's try this approach. :)

**Comment by ayoayco** [comment]
great job @Icyscools 🚀
