### ISSUE TITLE
[design]: project logo

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#51]
Hi, explorer! 🚀

Are you up for some SVG challenge? Create the project logo!

_*ehem*_ Maybe an 'R' that looks like a rocket? 😆

Of course, you can take inspiration in the framework that we love. See Astro's branding here: https://astro.build/press/

Acceptance criteria:
- add a logo that represents the project as an SVG file

**Comment by rsarthak** [comment]
Can you assign this to  me?

**Comment by rsarthak** [comment]
By the way I've created a SVG.
Link: https://github.com/rsarthak/SVG/tree/main

**Comment by ayoayco** [comment]
Hi @rsarthak, thank you for your interest to contribute! I have commented on your PR. Please try again :)

**Comment by rutvikk05** [comment]
Sent you the PR btw :)

**Comment by ayoayco** [comment]
Thanks @rutvikk05! Approved!
