### ISSUE TITLE
[feat]: add a new demo page

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#68]
Hi, explorer! 🚀

We have a `demo` app to play around with the packages (eg., astro-reactive-form).

Why not add some crazy examples? Create a new `.astro` page in the `pages` folder of the `demo` app. This new page will then be accessible on the browser. :)

For example, if you create a `crazy-form.astro` file in the `pages` directory, just open the address in the browser: `http://localhost:3000/crazy-form`

See our [contributing guide](https://github.com/ayoayco/astro-reactive-library/blob/main/CONTRIBUTING.md) for instructions to run the development server.

Read how to use the [reactive form package](https://github.com/ayoayco/astro-reactive-library/blob/main/packages/astro-reactive-form/README.md)

That's it! :)

Acceptance criteria:
1. a new .astro page in the demo app with as many different form control types as you can

**Comment by corners2wall** [comment]
Interesting, i would like use astro in future . Good reason for done this issue. 
Assign to me, i try new technology

**Comment by ayoayco** [comment]
Hi @corners2wall! 🎉

You are welcome to submit a PR for this. It is open for everyone. :)

**Comment by Savio629** [comment]
@ayoayco What should the .astro page contain?

**Comment by ayoayco** [comment]
A demo of the astro-reactive-form. You can find an example on the file index.astroOn Oct 13, 2022, at 9:26 PM, Savio Dias ***@***.***> wrote:﻿
@ayoayco What should the .astro page contain?

**Comment by itsagift** [comment]
Hi, I'm working on this but I'm stuck on the existing demo in index.astro -- when I click submit I get "This username is undefined" (no matter what I enter). I have the same problem in creating my own example. It seems like there's a disconnect in the getFormGroup function, since no HTML element is generated with the form name (in the example of the index.astro demo, "Simple Form").

Apologies if this should be its own separate issue. I am new to open source!

**Comment by ayoayco** [comment]
Yes separate issue indeed. Submit is still not working. This issue is just about creating a new page with a new example form. :)

**Comment by itsagift** [comment]
Going back to work on this -- I had a question about how to group radio components. In html you use the "name" property. Is there an equivalent here for form controls so that the user submits the checked value?

**Comment by ayoayco** [comment]
Hi @itsagift! We still have an open issue for radio groups #5 -- I understand there are some control components not ready to be added to the demo page for this. So I see this issue as an exploratory test of what components we need to work on next.
