### ISSUE TITLE
[docs]: add a 'description' for packages in README

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#8]
In the project README, add a 'description' for each of the packages in the project

**Comment by Manish5121** [comment]
Hey what do you want to put in the description,
I'm new to open source don't know about it much

**Comment by ayoayco** [comment]
Hi, @Manish5121 Glad to have you here! 🚀

It's okay, everyone is welcome to contribute. :)

For this issue, we want to add a description for each of our packages in the file `README.md` -- This is called a "MarkDown" file (that is why it has the extension .md). You will find here a table with columns Packages, Version, and Docs. You may need to learn (search google) how to write a table in MarkDown files, and then add a new 'Description' Column with the following values:

- astro-reactive-form - generate a dynamic form which can be modified programatically
- astro-reactive-validator - set of utilities for validating inputs
- astro-reactive-datagrid - generate a dynamic datagrid or table of values

Hope this helps. Let me know if you have any questions!

Enjoy! :)

**Comment by BabyElias** [comment]
Hey, I would like to take up this issue.

**Comment by ayoayco** [comment]
Hi @BabyElias thank you! You are welcome to submit a PR for this as well :)

**Comment by Manish5121** [comment]
Hey, @ayoayco i've made a pr please check it.
