### ISSUE TITLE
[fix]: demo app submit handling

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#86]
Right now when you click Submit on the demo app, you'll get a message:

```
Hi, My username is undefined. This Library is not awesome.
```

Ahhhhhhh 😱

Well, don't panic. The fix is simple... you just need to modify the `getFormGroup` method and the `Form.astro` component

_✨ Hint: `getFormGroup` is now returning `undefined` because it is not finding an element with the passed name._

**Comment by ayoayco** [comment]
Hi @slashgk! The method `getFormGroup(...)` needs to be updated to correctly return the <form> element rendered by `Form.astro` so that subsequent calls to `simpleForm.get(...)` will not be undefined. Hope this helps! Let me know if you have questions. :)

**Comment by itsagift** [comment]
gonna take a crack at this!

**Comment by ayoayco** [comment]
Significant changes to the project make this issue obsolete. Closing this now.
