### ISSUE TITLE
[feat]: implement a 'theme' property to the Form Component

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#9]
Hey, explorer! 🚀

Currently the Form.astro component in the project's astro-reactive-form package only accepts one input property (i.e., `formGroup`).

You can find this file in `packages/astro-reactive-form/Form.astro`. Follow the instructions in our [contributing guide](https://github.com/ayoayco/astro-reactive-library/blob/main/CONTRIBUTING.md) to get the project running.

In this issue, we add a new `theme` input property which will dynamically add a new class to the `<form>` element.

Acceptance criteria
1. `Form.astro` has a new optional prop 'theme'
2. The `<form>` element has a class attribute set to the value of this new 'theme' prop

Depending on the value passed to this input, we can later implement dynamic themes that will change the look and feel of our Form component.

**Comment by Chitvan14** [comment]
Hi @ayoayco, can you brief this issue? It will be helpful in understanding and working for it.

**Comment by ayoayco** [comment]
Hi @Chitvan14 ! Glad to have you on board! 🚀

Right now, if you run the project demo app, you will see that we have a Form component that is currently unstyled.

We want to keep it unstyled by default, but also allow our users to use a 'theme' property if they want, like so:

```astro
<!-- if they want a dark theme -->
<Form theme="dark" formGroups={[form]} />
```

For this issue, the goal is to add the 'theme' property to our `Form.astro` component. You don't have to fully implement the themes yourself.

For more information on Astro and implementation of components, you can check [the documentation](https://docs.astro.build/en/core-concepts/astro-components/)

Don't hesitate to ask, if anything is unclear! :)

**Comment by ayoayco** [comment]
I updated the issue description to add a clear Acceptance Criteria :)

**Comment by chaaals** [comment]
Hey @ayoayco would love to work on this, can you assign this to me?

**Comment by fazzaamiarso** [comment]
@ayoayco is anyone currently working on this issue? If not, I would like to help 😀.

**Comment by ayoayco** [comment]
Hi @fazzaamiarso! This has been inactive for some days, I think it's safe to say you can work on it :)
