### ISSUE TITLE
chore(packages): shared eslint rules

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/astro-reactive-library#94]
Set up the eslint configuration form all packages.

Right now we have separate eslint configuration for packages.

**Comment by Lalit3716** [comment]
Hi, I can try to do this. If you want you can assign me this!

**Comment by Lalit3716** [comment]
So we I get this right you want to have a single eslintrc  file in the root of packages directory and remove ESlint configuration from individual packages right ?

**Comment by Lalit3716** [comment]
Great then I will do it soon thanks for clearing!
